### ISSUE TITLE
Mobile "Fit to Screen"

### ISSUE THREAD

**Issue by MDXDave** [ganigeorgiev/presentator#27]
For me, a "Fit to Screen" option is very useful, because i don't want to convert all screens to the correct size (412x732 px).

I modified the code and add a "fit to screen" option. It works except of some weird movement when adding comments. It seems it have something todo with the overflow attribute changed by the _screen-comments.view.js_ file (L. 466 / 485).

**Comment by ganigeorgiev** [comment]
@MDXDave Is the desired result to expand/shrink the uploaded image if is smaller/larger than the specified screen size OR just to remove the border whitespaces around the image if the uploaded one is smaller and to hide the scrollbars if is larger?

**Comment by MDXDave** [comment]
The best way would be to convert the uploaded screens to a maximum size (e.g. 720x1280 ?) and show them within the container (732x412). My implementation just resize the original screens (in my case 2560x1440p, QHD) to fit the container.

**Comment by ganigeorgiev** [comment]
@MDXDave Currently when you upload a screen, the image that is shown in the preview is the original uploaded one (without any compression/cropping/resizing). Cropping/Resizing doesn't happen automatically on upload because the users have an option to change the project type after the screen is uploaded and that will require additional recroping/resizing. But the main issue with enabling auto cropping/resizing on upload is that there could be a hotspot or comment that is placed at a position which will be not visible if for example you switch the project type from desktop to mobile.

This weekend I'll try to find some free time and will take your use case in consideration.

**Comment by MDXDave** [comment]
What about just making a copy of the screens without tampering the original screens?

**Comment by ganigeorgiev** [comment]
@MDXDave Yes, that is an option, but still the other issue with the hotpost/comment positions remain.

**Comment by ganigeorgiev** [comment]
@MDXDave As I mentioned in https://github.com/ganigeorgiev/presentator/pull/28#issuecomment-313931082, this should be fixed in - https://github.com/ganigeorgiev/presentator/commit/c155e37d4156334b22e2a910ec55da0efba343e4.

Please reopen if you still encounter the issue.

**Comment by MDXDave** [comment]
@ganigeorgiev 

Thanks! Its working as expected :+1:
