### ISSUE TITLE
Edit Comments/Change position

### ISSUE THREAD

**Issue by MDXDave** [ganigeorgiev/presentator#31]
It should be possible to edit comments (maybe with change history?) and to move the comments.

Both at least for the administrator of the project or the author.

**Comment by ganigeorgiev** [comment]
@MDXDave I've enabled changing comment positions currently only for project administrators, since there is no easy way to tell if the guest created the comment - https://github.com/ganigeorgiev/presentator/commit/bbb1b9968ff217cc0e3ef8ac4c111b776f65ba55.
The fix will be deployed on production later this day.

Comments history and improvements to the comments section are planned for later releases (v1.4/5).
