### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by Arjoni** [ganigeorgiev/presentator#45]
Is there an admin panel to see who has signed up? After installing it, I can only register as a regular user.

**Comment by ganigeorgiev** [comment]
That's correct. There are no user roles, super admins, etc.

Only 1 level of hierarchy exist - all users are administrators to their own projects. You can share project ownership with another user/s by clicking on the "Manage admins" button located in the top left corner of your project sidebar:
![Project admins screenshot](https://i.cubeupload.com/hUgzOS.png)

**Comment by Arjoni** [comment]
Is there a way to disable registration?

**Comment by ganigeorgiev** [comment]
@Arjoni Unfortunately no, but I'll consider adding a config option in future releases (will be handled in another ticket).

**Comment by ganigeorgiev** [comment]
@Arjoni In v1.6.0 release you could  restrict email registrations by domain name(s) via the `allowedRegistrationDomains` optional parameter.
```
common/config/params-local.php
------------------------------
   
// list of email address domains that are allowed to register (eg. `['example.com', 'test.com']`)
// leave empty to disable the restriction
'allowedRegistrationDomains' => ['mysite.com'],
```

**Comment by Kiina** [comment]
Still no way to disable registration? I would love to disable registration and the default login and only allow users to login via the oauth providers.

**Comment by ganigeorgiev** [comment]
@Kiina This issue was for v1 and a lot of things have changed since then. In v2 you still cannot disable/hide the login form but [new parameters were added for more flexible administration](https://github.com/presentator/presentator/blob/2ae1673681bcddd81874047b389e933bd202081d/packages/api/config/params.php#L42-L50).

Could you elaborate more on your use case (you may also open a new issue so that others can join the discussion)?
