### ISSUE TITLE
Unable to create projects

### ISSUE THREAD

**Issue by kikminev** [ganigeorgiev/presentator#5]
One issue that I experienced after brand new registration was that I was unable to create projects. After clicking the create project and filling in all data the window refreshed without giving me an error or success message. I tried this several times. After logging out and again entering the user area the issue was gone and I was able to create projects. It could be a problem with new registrations only.

**Comment by ganigeorgiev** [comment]
Thanks for reporting the issue. It is fixed with c962a16db29fd0c519149f13c4ba888691d4f7f2.

The problem wasn't related with new user registrations and it occured due to mismatching type and subtype values (when Tablet or Mobile type was selected the default project subtype was having invalid value).

This kind of bugs are hard to find with the automation tests, so thanks again for pointing me out.
