### ISSUE TITLE
Error when adding new Admin

### ISSUE THREAD

**Issue by fuzenco** [ganigeorgiev/presentator#69]
Immediately upon typing in an email address for a *new* project admin in an already existing project, an error occurs (little modal at bottom-right of screen appears). I don’t know if this is a temporary issue.

**Comment by ganigeorgiev** [comment]
Thanks for reporting it.

The functionality for adding a new admin is working fine, but it should silently abort the pending admin search requests instead of displaying the error message (_each time when you type an ajax request is send and if there are still pending incomplete requests they are aborted, so only the "last key press" is taken into account_).

It will be fixed in the next release.

**Comment by fuzenco** [comment]
Thank you!

**Comment by ganigeorgiev** [comment]
A hotfix was implemented and released as v1.8.2.

**Comment by fuzenco** [comment]
Still don't see this fixed in 1.8.2. I emptied my cashes and restarted both browsers (Safari and Chrome). The error is no longer shown but no admin is added after hitting Return on the keyboard. Maybe I misunderstood about the admin being added fixed versus the error being fixed on this hot fix.

**Comment by ganigeorgiev** [comment]
"Enter" keyboard event is not handled. You have to select the admin suggestion via mouse click from the dropdown list.

Although currently only 1 result could be returned because of the required full email address matching, there is a config param (https://github.com/ganigeorgiev/presentator/blob/master/common/config/params.php#L16) that can enable searching for project admins by only part of their email address or name.

I'll consider adding keyboard navigation support for the suggestion dropdowns in future releases but this will be handled in another issue.

**Comment by fuzenco** [comment]
Must be confusion on my end. I thought that if we entered an email address we could invite that person whether or not they were in the same domain @company.com. But if as you say, it retrieves a list of matching admins, well how do those admins get entered into the system? I see nowhere in the Dashboard for settings where that can be done.
