### ISSUE TITLE
Email addresses publicly available

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#7]
Had some minutes free and played around trying to trick the system.
Found out that when using the option to add project admins the email address of all users within the system are searchable and returned if there is a match.
As far as I know, other services which offer such functionality are having additional option within the user profile settings page or similar, which allow them to make such information it public or not.
Think this is a serious privacy problem and this is not mentioned within the "Terms and Conditions".

**Comment by ganigeorgiev** [comment]
You are right. I'll add a new user setting and will limit the users search to full email address only.

**Comment by ganigeorgiev** [comment]
Fixed with c61e35f482a791af57051daf56454afc4e41eb41.

For those who host the application themselves and want to enable the fuzzy search, there is a new parameter added `fuzzyUsersSearch` which can be overwritten in `common\config\params-local.php` .
By default the parameter is `false`, which means that user match will be returned only if the its email address is typed exactly the same.
