### ISSUE TITLE
Correct translations and language use

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#8]
Only to comment, but it is a bit difficult to know from Transifex where the translation string will be used. The translation can vary based on the context. :(

What I think is important to point is what should be the language used within the translations: formal or informal?
I've seen different usages now: Polish is using informal form while Bulgarian is formal. As you fro sure know, based on the language, the writing will be different if you use one or other variation.

**Comment by ganigeorgiev** [comment]
For the unspecified context - maybe you are right. I'll try to find some time and will separate the strings in more than 2 translation domains (currently there are only _app_ and _email_).

Until then, I suggest you to use the informal form to be consistent with the Polish translations  (I'll update the Bulgarian translations in the next few days).

I'll leave the discussion open, so any other suggestions are also welcome.

**Comment by ganigeorgiev** [comment]
Just to let you know, through Transifex I've added screenshots and comments to some translation strings.

Until I add additional translation domains, If a string context is not clear enough, please create a comment as you mention me @gani.georgiev (otherwise I don't receive notification) in Transifex and I will try to explain its context or add a screenshot.

**Comment by ganigeorgiev** [comment]
Closing the issue for now.

As described earlier - if the context is not clear enough, please mention me `@gani.georgiev` in Transifex comment and I'll try to explain its context or add a screenshot(s).
