### ISSUE TITLE
Presentator direction/goal

### ISSUE THREAD

**Issue by gt0p** [ganigeorgiev/presentator#80]
Im exciting that I have found an open source tool for designers. I also tried to set up the project in my own server because the idea of a gitlab-like tool for designers is awesome.

Nevertheless, I would like to ask something about to the overall approach that the tool follows to solve certain common problems. 
The period in which more and more design tools leave from the area of designs as images (and so hotspots as overlays etc), you follow invision's old method. So, the question is why you chose to represent designs (dynamic) to static images and not a component-based approach ?

**Comment by ganigeorgiev** [comment]
Presentator has only one simple goal - to easy share designs with clients.

The platform was initially created because I and my coworkers were having troubles working with Invision and we needed a self hosted alternative due to various legal specifications of the projects in which we were involved (ISO certificates, privacy and license agreements, etc.). 

_**"Why you chose to represent designs (dynamic) to static images and not a component-based approach?"**_
Short answer - in my opinion (_at least for now_) it's easier this way both for designers and clients.
It doesn't require changing your day-to-day workflow and the designer is free to use Photoshop, Sketch or whatever tool he/she is used to.
