### ISSUE TITLE
Hotspots and their destinations are mystery

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#9]
Hotspots, in to appear there must be a user interaction (currently "click" somewhere) which is kinda guess if there is something somewhere. Different than the comment indicators which are directly loaded and shown.
And the destination of the hotspot is not present which makes it scary if you don't know where will land.

**Comment by ganigeorgiev** [comment]
This behavior is intended (and was also suggested during beta) for the project previews to prevent messing with the design that the user present, because it is possible to create a very large hotspot that could cover the screen.

If you click on nonhotspot area there should be hint (for a half a second or so) that displays all available hotspots.

I will consider to increase the hint timeout and add a keyboard shortcut to toggle the hotspots visiblity.

**Comment by ganigeorgiev** [comment]
Increased the hint timeout (combined with the css transition now is nearly 1s) and added the toggle shortcut "**shift + h**" to force hotspots visibility.

Missing info/documentation about all available shortcuts will be handled in another issue - https://github.com/ganigeorgiev/presentator/issues/15
